typography_spectrum: 0.38672117702662945
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5713549132924527
  lightness: 0.38815940800122917
  saturation: 0.8804769380949438
  rhythmicContrast: 0.8021690924651921
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.21388554479926825
analytics:
  google: null
  facebook: null
  twitter: null
name: clomads
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Gay as Fuck
purpose: []
